<?php  

namespace Database\Seeders;  

use Illuminate\Database\Seeder;  
use Illuminate\Support\Facades\DB;  

class ProductsTableSeeder extends Seeder  
{  
    public function run()  
    {  
        DB::table('products')->insert([  
            [  
                'id' => 1254,  
                'name' => 'Triangulation торт силиконовая форма ручной работы',  
                'sku' => 'HM-006',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/handmade/triangulation_cake/1.jpg',  
                'stock_quantity' => 35,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 51,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1255,  
                'name' => 'The Cells торт силиконовая форма ручной работы',  
                'sku' => 'HM-007',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/handmade/Cells_cake/1.jpg',  
                'stock_quantity' => 39,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 52,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1256,  
                'name' => 'Heart силиконовая форма для торта',  
                'sku' => 'B002',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/Factory/heart_cake/1.jpeg',  
                'stock_quantity' => 42,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 53,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1257,  
                'name' => 'Spheres small силиконовая форма для пирожного Сферы',  
                'sku' => 'S001',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/Factory/spheres_mini/1.jpg',  
                'stock_quantity' => 192,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 54,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1258,  
                'name' => 'Pentagon силиконовая форма для пирожных Пентагон',  
                'sku' => 'S002',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/Factory/pentagon_mini/1.jpeg',  
                'stock_quantity' => 154,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 55,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1259,  
                'name' => 'Folding торт силиконовая форма ручной работы',  
                'sku' => 'HM-011',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/handmade/folding_cake/1.jpg',  
                'stock_quantity' => 34,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 73,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1260,  
                'name' => 'XXL Spheres торт силиконовая форма ручной работы',  
                'sku' => 'HM-021',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/handmade/XXL_spheres/1.jpg',  
                'stock_quantity' => 35,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 58,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1261,  
                'name' => 'Cluster торт силиконовая форма ручной работы',  
                'sku' => 'HM-010',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/handmade/cluster_cake/1.jpg',  
                'stock_quantity' => 34,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 59,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1262,  
                'name' => 'Shapka торт силиконовая форма ручной работы',  
                'sku' => 'HM-005',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/handmade/Shapka_cake/1.jpg',  
                'stock_quantity' => 42,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 72,  
                'product_id_hor' => null,  
                'created_at' => '2025-07-16 07:47:42',  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1263,  
                'name' => 'Spheres силиконовая форма для торта Сферы',  
                'sku' => 'B003',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/Factory/spheres_cake/1.jpeg',  
                'stock_quantity' => 111,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 62,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1264,  
                'name' => 'Ferro силиконовая форма для торта Ферро',  
                'sku' => 'B004',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/Factory/ferro_cake/1.jpeg',  
                'stock_quantity' => 87,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 63,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],  
            [  
                'id' => 1265,  
                'name' => 'Cubik силиконовая форма для торта от Silikomart и Динара Касько ',  
                'sku' => '20.343.87.0065',  
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/Factory/cubik/1.jpeg',  
                'stock_quantity' => 33,  
                'desired_stock_quantity' => 0,  
                'ordered_for_production' => 0,  
                'is_active' => 0,  
                'product_id_oc' => 71,  
                'product_id_hor' => null,  
                'created_at' => null,  
                'updated_at' => null,  
            ],
            [
                'id' => 1319,
                'name' => 'Заяц торт силиконовая форма ручной работы ',
                'sku' => 'HM-033',
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/handmade/XXL_Bunny_cake/1.jpg',
                'stock_quantity' => 36,
                'desired_stock_quantity' => 0,
                'ordered_for_production' => 0,
                'is_active' => 1,
                'product_id_oc' => 240,
                'product_id_hor' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1379,
                'name' => 'Savoiardi торт силиконовая форма ручной работы',
                'sku' => 'HM-078',
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/handmade/Savoiardi_cake/1.jpg',
                'stock_quantity' => 33,
                'desired_stock_quantity' => 0,
                'ordered_for_production' => 0,
                'is_active' => 1,
                'product_id_oc' => 310,
                'product_id_hor' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1835,
                'name' => 'test2new',
                'sku' => 'test2new',
                'image' => 'https://dinara.david-freedman.com.ua/image/',
                'stock_quantity' => 113,
                'desired_stock_quantity' => 0,
                'ordered_for_production' => 0,
                'is_active' => 1,
                'product_id_oc' => 387,
                'product_id_hor' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1837,
                'name' => 'Chocolate block силиконовая форма для торта',
                'sku' => 'B001',
                'image' => 'https://dinara.david-freedman.com.ua/image/catalog/goods/Factory/chocolate_block/1.jpg',
                'stock_quantity' => 288,
                'desired_stock_quantity' => 0,
                'ordered_for_production' => 0,
                'is_active' => 0,
                'product_id_oc' => 50,
                'product_id_hor' => null,
                'created_at' => '2025-07-19 04:53:03',
                'updated_at' => null,
            ],
        ]);
    }
}